### PR TITLE
Feature/gitpod

### PR DESCRIPTION
**Pull request by domwoe**
Our gitpod expert @frank-bee is currently on vacation, but I tried to setup an initial version.

You can try it here: https://gitpod.io/#https://github.com/domwoe/indy-did-method/tree/feature/gitpod

### CODE REVIEW

**Comment by swcurran** [comment]
I wasn’t sure how to use this.  I was expecting a browser coming up showing the rendered spec so that I could refresh as I was editing.  Also, I’m not quite sure how the PR flow works in GitPod — can I make and sign a PR from the Pod?  I’m assuming so...

**Comment by swcurran** [comment]
Also now there is a conflict in the readme…. You’re welcome for that :-)

**Comment by domwoe** [comment]
hm, it is working for me. I added a small instructions section to the readme. But I'm also not sure if people would really use it... 
If you'd like to merge this PR at some point, please squash. There's too much trial and error here... ;)

**Review by swcurran — APPROVED** [review]
That worked this time -- not sure why it wasn't.  Let's give it a go.

**Pull request merged**
